twitch-app {
  poller {
    interval = 60s
    recently-live-window = 5m
    parallel-categories = 5
    streams-page-size = 100
  }
  search {
    page-size = 20
  }
  sse {
    reconnect-delay = 5s
  }
  email {
    from = "noreply@example.com"
    from-name = "Twitch App"
  }
}
